Vagrant::Config.run do |config|
  config.vm.box = "tabula"
  config.vm.box_url = "http://dl.dropbox.com/u/29645873/vagrants/tabula.box"

  # config.vm.boot_mode = :gui
  config.ssh.forward_x11 = true

end
